site_name: Amranidev Blog
site_author: Amrani Houssain
repo_url: https://github.com/amranidev
theme: flatly

pages:
- Home: 'index.md'
- Blog: 
    - 'Split your laravel app': 'split-your-laravel-app.md'
- Project:
    - 'Scaffold-interface': 'scaffold-interface.md'
    - 'Ajaxis': 'ajaxis.md'
    - 'Lpackager': 'lpackager.md'

